### PR TITLE
Make package Capacitor 6 compatible

### PR DESCRIPTION
**Pull request by piotr-cz**
To test:

```console
npm install github:piotr-cz/capacitor-android-dark-mode-support#feature/capacitor-6
```

### CODE REVIEW

**Comment by robingenz** [comment]
This repository is deprecated as this plugin should no longer be needed, see [this comment](https://github.com/ionic-team/capacitor/issues/4677#issuecomment-1126274884). For this reason, I am closing this PR.

**Comment by piotr-cz** [comment]
> This repository is deprecated as this plugin should no longer be needed, see [this comment](https://github.com/ionic-team/capacitor/issues/4677#issuecomment-1126274884). For this reason, I am closing this PR.

That comment applies to WebView versions >= 100, but Capacitor [requires](https://capacitorjs.com/docs/android#android-support)  >= 60.

There is an edge case when user installs a capacitor app, but doesn't update WebView or is not able to update it (on older Android version).

See https://stackoverflow.com/a/61643614/1012616

**Comment by robingenz** [comment]
Okay, I will publish a Capacitor 6 compatible version in https://github.com/capawesome-team/capacitor-plugins.

**Comment by robingenz** [comment]
See https://github.com/capawesome-team/capacitor-plugins/pull/308

**Pull request closed without merging**
